### ISSUE TITLE
Is possible to include chatter in my template ?

### ISSUE THREAD

**Issue by voneAbides** [dibs-devs/chatter#12]
Hello.
I want chat on the top of my main page. Is it possible ?

**Comment by ishtiaque06** [comment]
Hello! To clarify, you want your main page to be able to do its thing and then have a chat module somewhere in the corner like Facebook does?

**Comment by voneAbides** [comment]
Yes, but I want it in the middle.

**Comment by ishtiaque06** [comment]
It would definitely be possible! Django Chatter has a context processor that you can use to load the chatrooms the logged in user belongs to on every page load. You can use this to display all chatrooms that a user belongs to inside a `<div>` on your main page. I would suggest taking a look at the `templates/` and the `static/` folders in this repo to figure out how the whole chat functionality works. In essence, you have to connect to a WebSocket in your main page using the relevant chatroom's ID. I do it using (`chat-window.js`)[https://github.com/dibs-devs/chatter/blob/master/django_chatter/static/js/chat-window.js]. If you can do this on your template, I don't see why you can't use the chat functionalities.

Of course, to be able to do all that you'd need to have intermediate Django experience. But the tools are there. You just have to incorporate the right elements needed by the JS source I mentioned above for your chat functionality to work.

**Comment by voneAbides** [comment]
Thank you very much for answer. This project will be big success !

**Comment by ishtiaque06** [comment]
Thanks! Let me know if you end up implementing this and want help.
